equipment/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import *

router = DefaultRouter()
router.register('equipment_api', EquipmentViewSet, basename='equipment_api')


urlpatterns = [
    path('equipment/', EquipmentViewSet.as_view({'get': 'list'}), name='equipment'),
    path('staff/', StaffList.as_view(), name='staff'),
    path('', MainPage.as_view(), name='main_page'),
    path('register/', RegisterFormView.as_view()),
    path('login/', LoginFormView.as_view()),
    path('logout/', LogoutView.as_view(next_page='/')),
    path('equipment_api/', include(router.urls)),
]

mydiploma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('equipment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipment/models.py
from django.db import models

class Position(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Employee(models.Model):
    name = models.CharField(max_length=50)
    birth_year = models.PositiveSmallIntegerField()
    position = models.ForeignKey(Position, on_delete=models.CASCADE, blank=True, null=True)
    photo = models.ImageField(upload_to='media/photo/', blank=True, null=True)

    def __str__(self):
        return self.name

class Equipment(models.Model):
    name = models.CharField(max_length=50)
    serial = models.PositiveSmallIntegerField()
    in_use = models.ForeignKey(Employee, on_delete=models.SET_NULL, blank=True, null=True)
    image = models.ImageField(upload_to='media/images/', blank=True, null=True)

    def __str__(self):
        return self.name


class PositionQuantity(models.Model):
    position_name = models.OneToOneField(Position, on_delete=models.CASCADE, primary_key=True,)
    position_quantity = models.PositiveSmallIntegerField()
    position_description = models.TextField(blank=True, null=True)

equipment/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=commit)
        user.email = self.cleaned_data("email")
        if commit:
            user.save()
        return user

equipment/views.py
from django.views.generic import TemplateView

from rest_framework import permissions
from rest_framework.viewsets import ModelViewSet

from .models import *
from .serializers import *

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import ListView, FormView


class EquipmentViewSet(ModelViewSet):
    queryset = Equipment.objects.all()
    serializer_class = EquipmentSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class StaffList(ListView):
    model = Employee
    template_name = 'staff.html'


class MainPage(TemplateView):
    template_name = 'main.html'


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(RegisterFormView, self).form_invalid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = '/'

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)

templates/equipment.html
<h1>Список имущества фирмы Рога и Копыта</h1>
<ul>

  {% for equipment in equipment_list %}
    <h2>{{ equipment.name }}</h2>
    <img src="{{ equipment.image.url}}" alt="{{ equipment.name }}" width="500">
    <br>Ответственный - {{ equipment.in_use }}
  {% endfor %}
</ul>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}

  {% for field in form %}
   <div class="form-group">
     <label for="">{{field.label}}</label>
     {{field}}
     {% if field.errors %}
     <p>{{}field.errors}</p>
     {% endif %}
   </div>
  {% endfor %}
  <button type="submit">Войти</button>
</form>
</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Рога и копыта</title>
    <meta name="keywords" content="фирма, прикол, рога и копыта">
    <meta name="desctription" content="Это тренировочный сайт для фирмы Рога и копыта">
    <link rel="shortcut icon" href="https://image.flaticon.com/icons/png/512/85/85215.png">
</head>
<body>
<h1>ООО "Рога и копыта"</h1>
<br>Приветствуем вас на сайте фирмы Рога и копыта!
<br>
<br>
<br>Вот тут вы можете почитать: <a href="/staff/" target="_blank">про наших работников</a>
<br>
<br>
<br>А здесь написано <a href="/equipment/" target="_blank">про наше передовое оборудование</a>
<br>
<br>
<br>
  {% if user.is_authenticated %}
    привет, {{user.username}} !
    <a href="logout/">выйти ({{user.username}})</a>
  {% else %}
    Работаешь в Рога и копыта? Залогинься!
<br>
<br>
    <a href="register/">Регистрация на сайте</a>
    <a href="login/">Авторизация</a>
  {% endif %}

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
<form action="" method="post">{% csrf_token %}

  {% for field in form %}
     <label for="">{{field.label}}</label>
    <div>{{field}}</div>
     {% if field.errors %}
     <p>{{field.errors}}</p>
     {% endif %}
  {% endfor %}
  <button type="submit">Зарегистрироваться</button>
</form>
</body>
</html>

templates/staff.html
<h1>Список персонала фирмы Рога и Копыта</h1>
<ul>

  {% for staff in employee_list %}
    <h2>{{ staff.name }} - {{ staff.position }}</h2>
    <img src="{{ staff.photo.url}}" alt="{{ staff.name }}" width="500" title="{{ staff.position }}">

  {% endfor %}
</ul>